package midiblocks;
import scales.Note;

/**
 * The subject interface allows observers to observe events generated by
 * the subject.
 * @author Lisa Liu-Thorrold
 *
 */
public interface Subject {
    void registerObserver(Observer observer);

    void removeObserver(Observer observer);

    void notifyObservers(Note note, Boolean noteOn);
    
    void removeAllObservers();
}